name: JAR Dist

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rando
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'rando'
        repository: 'champred/UPR-Android'
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Override gradle settings
      run: echo "include ':upr'" > settings.gradle
    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 :upr:jar
    - uses: actions/upload-artifact@v4
      with:
        name: JAR
        path: rando/upr/build/libs/upr.jar
